name: py39
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - pip
  - pip:
    - absl-py==2.3.1
    - addict==2.4.0
    - anyio==3.6.2
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.2.3
    - asttokens==2.2.1
    - attrs==22.2.0
    - backcall==0.2.0
    - beautifulsoup4==4.11.2
    - bleach==6.1.0
    - cachetools==5.5.2
    - certifi
    - cffi==1.15.1
    - charset-normalizer==3.0.1
    - click==8.1.3
    - comm==0.2.2
    - ConfigArgParse==1.5.3
    - contourpy==1.1.1
    - cycler==0.12.1
    - Cython==0.29.33
    - dash==2.7.1
    - dash-core-components==2.0.0
    - dash-html-components==2.0.0
    - dash-table==5.0.0
    - debugpy==1.8.15
    - decorator==5.1.1
    - defusedxml==0.7.1
    - entrypoints==0.4
    - executing==1.2.0
    - fastjsonschema==2.16.2
    - filelock==3.16.1
    - Flask==2.2.2
    - fonttools==4.57.0
    - fqdn==1.5.1
    - fsspec==2024.3.1
    - fvcore==0.1.5.post20221221
    - google-api-core==2.11.0
    - google-api-python-client==2.79.0
    - google-auth==2.16.1
    - google-auth-httplib2==0.1.0
    - google-auth-oauthlib==0.4.6
    - googleapis-common-protos==1.58.0
    - graphviz==0.20.3
    - grpcio==1.70.0
    - hf-xet==1.1.5
    - httplib2==0.21.0
    - huggingface-hub==0.33.4
    - idna==3.4
    - importlib-metadata==6.0.0
    - importlib-resources==5.10.2
    - iopath==0.1.10
    - ipykernel==6.29.5
    - ipython==8.8.0
    - ipython-genutils==0.2.0
    - ipywidgets==8.0.4
    - isoduration==20.11.0
    - itsdangerous==2.1.2
    - jedi==0.18.2
    - Jinja2==3.1.2
    - joblib==1.4.2
    - jsonpointer==2.3
    - jsonschema==4.17.3
    - jupyter-events==0.6.3
    - jupyter-http-over-ws==0.0.8
    - jupyter_client==8.0.3
    - jupyter_core==5.2.0
    - jupyter_server==2.3.0
    - jupyter_server_terminals==0.4.4
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==3.0.5
    - kiwisolver==1.4.7
    - Markdown==3.7
    - MarkupSafe==2.1.2
    - matplotlib==3.7.5
    - matplotlib-inline==0.1.6
    - mistune==2.0.5
    - mpmath==1.3.0
    - nbclassic==0.5.2
    - nbclient==0.7.2
    - nbconvert==7.2.9
    - nbformat==5.5.0
    - nest-asyncio==1.6.0
    - networkx==3.1
    - notebook==6.5.2
    - notebook_shim==0.2.2
    - numpy==1.24.1
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-nccl-cu12==2.20.5
    - nvidia-nvjitlink-cu12==12.9.86
    - nvidia-nvtx-cu12==12.1.105
    - oauth2client==4.1.3
    - oauthlib==3.2.2
    - open3d==0.16.0
    - packaging==25.0
    - pandas==1.5.3
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==10.4.0
    - pkgutil_resolve_name==1.3.10
    - platformdirs==4.3.6
    - plotly==5.12.0
    - plyfile==0.7.4
    - portalocker==3.0.0
    - prometheus-client==0.16.0
    - prompt-toolkit==3.0.36
    - protobuf==3.20.3
    - psutil==7.0.0
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyasn1==0.6.1
    - pyasn1_modules==0.4.2
    - pycparser==2.21
    - PyDrive==1.3.1
    - Pygments==2.14.0
    - pyparsing==3.1.4
    - pyquaternion==0.9.9
    - pyrsistent==0.19.3
    - python-dateutil==2.8.2
    - python-json-logger==2.0.7
    - pytz==2022.7.1
    - PyYAML==6.0
    - pyzmq==25.0.0
    - remotezip==0.12.1
    - requests==2.28.2
    - requests-oauthlib==2.0.0
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rsa==4.9.1
    - safetensors==0.5.3
    - scikit-learn==1.3.2
    - scipy==1.10.0
    - Send2Trash==1.8.0
    - six==1.16.0
    - sniffio==1.3.1
    - soupsieve==2.4
    - stack-data==0.6.2
    - sympy==1.13.3
    - tabulate==0.9.0
    - tenacity==8.1.0
    - tensorboard==2.11.2
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - termcolor==2.4.0
    - terminado==0.17.1
    - thop==0.1.1.post2209072238
    - threadpoolctl==3.5.0
    - timm==1.0.17
    - tinycss2==1.2.1
#    - torch==1.12.1+cu113
#    - torch-scatter==2.1.2
#    - torchaudio==0.12.1+cu113
    - torchinfo==1.8.0
    - torchsummary==1.5.1
#    - torchvision==0.13.1+cu113
    - torchviz==0.0.3
    - tornado==6.2
    - tqdm==4.64.1
    - traitlets==5.8.1
    - trimesh==3.18.1
    - triton==3.0.0
    - typing_extensions==4.13.2
    - uri-template==1.2.0
    - uritemplate==4.1.1
    - urllib3==1.26.14
    - usd-core==23.2
    - wcwidth==0.2.6
    - webcolors==1.12
    - webencodings==0.5.1
    - websocket-client==1.5.1
    - Werkzeug==2.2.2
    - wget==3.2
    - widgetsnbextension==4.0.5
    - yacs==0.1.8
    - zipp==3.12.0